spring:
  application:
    name: spring-boot-speed-skill-system

  profiles:
    active: dev

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.104:3306/skillspeedsystem?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 500
      idle-timeout: 600000
      maximum-pool-size: 1000
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    host: 192.168.0.104
    port: 6379
    timeout: 10
    password: 123456
    poolMaxTotal: 1000
    poolMaxIdle: 1000
    poolMaxWait: 500

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  resources:
    add-mappings: true
    cache:
      period: 3600
      cachecontrol:
        max-age: 3600
    chain:
      cache: true
      enabled: true
      html-application-cache: true
      compressed: true
    static-locations: classpath:/static/

mybatis:
  mapper-locations: classpath:/mapper/*.xml

logging:
  file: ../logs/spring-boot-speed-skill-system.log
  level.org.springframework.web: DEBUG